<script setup lang="ts">
    function onAnimationStart(ev: AnimationEvent) {
        // const el = ev.target as HTMLElement ?? undefined;
        //     el.classList.add("h-0", "fade-in-top");
    }
    function onAnimationEnd(ev: AnimationEvent) {
        // const el = ev.target as HTMLElement ?? undefined;
        // if (el.classList.contains("fade-in-top")) {
        //     el.classList.remove("h-0", "fade-in-top");
        // }
    }
</script>

<template>
    <div class="fade-in-top transition-[height]"
        @animationstart="onAnimationStart"
        @animationend="onAnimationEnd"
    >
        <slot />
    </div>
    
</template>

<style scoped>
.fade-in-top {
	-webkit-animation: fade-in-top 0.6s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
	        animation: fade-in-top 0.6s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2024-3-5 10:19:9
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in-top
 * ----------------------------------------
 */
 @-webkit-keyframes fade-in-top {
  0% {
    -webkit-transform: translateY(-50px);
            transform: translateY(-50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}
@keyframes fade-in-top {
  0% {
    -webkit-transform: translateY(-50px);
            transform: translateY(-50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}


</style>
