<script setup lang="ts">
    defineProps<{
        message: string,
        show: boolean,
    }>();

    function onAnimationEnd(ev: AnimationEvent) {
        const el = ev.target as HTMLElement ?? undefined;
        if (el.classList.contains("scale-in-ver-top")) {
            el.classList.remove("h-0", "scale-in-ver-top");
        }
    }
</script>

<template>
    <Alert
        type="error"
        :show="show"
        class="scale-in-ver-top transition-[height] h-0 overflow-hidden"
        @animationend="onAnimationEnd"
    >
        {{ message }}
    </Alert>
</template>

<style scoped>
    /* ----------------------------------------------
    * Generated by Animista on 2024-3-1 23:45:39
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */
    .scale-in-ver-top{-webkit-animation:scale-in-ver-top .5s cubic-bezier(.6,.04,.98,.335);animation:scale-in-ver-top .5s cubic-bezier(.6,.04,.98,.335)}
    @-webkit-keyframes scale-in-ver-top{0%{-webkit-transform:scaleY(0);transform:scaleY(0);-webkit-transform-origin:100% 0;transform-origin:100% 0;opacity:1}100%{-webkit-transform:scaleY(1);transform:scaleY(1);-webkit-transform-origin:100% 0;transform-origin:100% 0;opacity:1}}@keyframes scale-in-ver-top{0%{-webkit-transform:scaleY(0);transform:scaleY(0);-webkit-transform-origin:100% 0;transform-origin:100% 0;opacity:1}100%{-webkit-transform:scaleY(1);transform:scaleY(1);-webkit-transform-origin:100% 0;transform-origin:100% 0;opacity:1}}
    
    /* 
    .scale-out-ver-top{-webkit-animation:scale-out-ver-top .25s cubic-bezier(.25,.46,.45,.94) both;animation:scale-out-ver-top .25s cubic-bezier(.25,.46,.45,.94) both}
    @-webkit-keyframes scale-out-ver-top{0%{-webkit-transform:scaleY(1);transform:scaleY(1);-webkit-transform-origin:100% 0;transform-origin:100% 0;opacity:1}100%{-webkit-transform:scaleY(0);transform:scaleY(0);-webkit-transform-origin:100% 0;transform-origin:100% 0;opacity:1}}@keyframes scale-out-ver-top{0%{-webkit-transform:scaleY(1);transform:scaleY(1);-webkit-transform-origin:100% 0;transform-origin:100% 0;opacity:1}100%{-webkit-transform:scaleY(0);transform:scaleY(0);-webkit-transform-origin:100% 0;transform-origin:100% 0;opacity:1}}
    */
</style>
